Test outputs (#214)
* attempt step outputs on tests

* swap table for bullet points

* move success condition out of python

* step logic is tricky

* finish adding test outputs

diff --git a/tests/docker/action.yml b/tests/docker/action.yml
--- a/tests/docker/action.yml
+++ b/tests/docker/action.yml
@@ -14,6 +14,11 @@ runs:
       shell: bash
       run: |
         docker run hello-world
+        if $? -ne 0; then
+          echo "- ❌ docker run hello-world failed" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "- ✅ docker run hello-world succeeded" >> $GITHUB_STEP_SUMMARY
+        fi
 
     - name: "Docker network info"
       shell: bash
@@ -24,3 +29,8 @@ runs:
       shell: bash
       run: |
         docker-compose --version
+        if $? -ne 0; then
+          echo "- ❌ docker-compose check failed" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "- ✅ docker-compose check succeeded" >> $GITHUB_STEP_SUMMARY
+        fi
diff --git a/tests/sudo-works/action.yml b/tests/sudo-works/action.yml
--- a/tests/sudo-works/action.yml
+++ b/tests/sudo-works/action.yml
@@ -8,4 +8,12 @@ runs:
     - name: "Sudo fails"
       shell: bash
       run: |
-        sudo echo "sudo works"
+        if [ $(sudo echo "sudo works") -eq 0 ]; then
+          echo "sudo succeeds"
+          echo "- ✅ sudo succeeds" >> $GITHUB_STEP_SUMMARY
+          exit 0
+        else
+          echo "sudo failed"
+          echo "- ❌ sudo failed" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi s
